### ISSUE TITLE
Proposal to change the name of the project to Docker-iOS

### ISSUE THREAD

**Issue by sickcodes** [sickcodes/Docker-eyeOS#9]
Should I change the name?

**Comment by ItzYanick** [comment]
yes

**Comment by darkvertex** [comment]
I'm not a lawyer but I reckon it might be wise to avoid [trademarked names](https://www.apple.com/legal/intellectual-property/trademark/appletmlist.html) in the repo name.

**Comment by sickcodes** [comment]
> I'm not a lawyer but I reckon it might be wise to avoid [trademarked names](https://www.apple.com/legal/intellectual-property/trademark/appletmlist.html) in the repo name.

True, that was the original thought anyway, even polled it on twitter.

I'll keep as is for now!
